version: '3'
services:
  qdrand-db:
    restart: always
    container_name: qdrant-db
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
volumes:
  qdrant_storage: